wallpaper {
    monitor = HDMI-A-2
    path = ~/.bg/void.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/.bg/green.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.bg/rust.jpg
    fit_mode = cover
}
